# ################################################################
# ################################################################
## PLOTTING FUNCTIONS:
 
#################################################
#################################################
##  plot.integrals:
##    Function that generates oracle influence measure
##    plots, coloring hubs and non-hubs differently.
##
##  INPUTS
##    eig   : object eigen(M) of a covariance/correlation 
##              matrix M.
##    args  : object generated by CreateParameters(), which
##              matches the parameters associated to the 
##              matrix M.
##    main  : title of plot.
##    
##  OUTPUT
##    .inf_meas_curve :
##            Matrix where ith-row corresponds to influence
##            measure curve for i-th variable in the matrix M.
plot.integrals <- function(eig, args, main) {
  .inf_meas_curve <- matrix(rep(0, args$p * args$p), ncol = args$p)
  .inf_meas_curve[, 1] <- eig$vectors[, args$p]^2
  for(.i in 2:args$p){
    .inf_meas_curve[, .i] <- .inf_meas_curve[, .i - 1] + eig$vectors[, args$p - .i + 1]^2
  }
  .weights <- apply(.inf_meas_curve[, 1:args$threshold],
                   MARGIN = 1,
                   sum)
  skew <- skewness(.weights)
  ## Plot of integrals
  plot(c(0, 0), col = "white",
       xlim = c(0, args$p),
       ylim = c(0, 1),
       main = main,
       xlab = "No. of Eigenvectors",
       ylab = "Influence Measure Value")
  for (.j in args$p:1) {
    if (.j < args$r+1) lines(x = 1:args$p, y = .inf_meas_curve[.j, ], col = cbPalette[1])
    if (.j > args$r) lines(x = 1:args$p, y = .inf_meas_curve[.j, ], col = cbPalette[2])
  }
  abline(v = args$threshold, col = "red")

  return(.inf_meas_curve)
}
